apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeneuron-operator
  namespace: kube-neuron
  labels:
    app.kubernetes.io/name: kube-neuron
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
