apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubeneuron_v1alpha1_kubeneuron.yaml
  - kubeneuron_v1alpha1_gpuplaybook.yaml
  - kubeneuron_v1alpha1_gpuremediationpolicy.yaml
