//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRuntimeActionPolicy) DeepCopyInto(out *AcceleratorRuntimeActionPolicy) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]AcceleratorRuntimeScope, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRuntimeActionPolicy.
func (in *AcceleratorRuntimeActionPolicy) DeepCopy() *AcceleratorRuntimeActionPolicy {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRuntimeActionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRuntimeProfile) DeepCopyInto(out *AcceleratorRuntimeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRuntimeProfile.
func (in *AcceleratorRuntimeProfile) DeepCopy() *AcceleratorRuntimeProfile {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRuntimeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorRuntimeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRuntimeProfileList) DeepCopyInto(out *AcceleratorRuntimeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorRuntimeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRuntimeProfileList.
func (in *AcceleratorRuntimeProfileList) DeepCopy() *AcceleratorRuntimeProfileList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRuntimeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorRuntimeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRuntimeProfileSpec) DeepCopyInto(out *AcceleratorRuntimeProfileSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	out.MaxReportAge = in.MaxReportAge
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]AcceleratorRuntimeActionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRuntimeProfileSpec.
func (in *AcceleratorRuntimeProfileSpec) DeepCopy() *AcceleratorRuntimeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRuntimeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRuntimeProfileStatus) DeepCopyInto(out *AcceleratorRuntimeProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRuntimeProfileStatus.
func (in *AcceleratorRuntimeProfileStatus) DeepCopy() *AcceleratorRuntimeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRuntimeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostTooling != nil {
		in, out := &in.HostTooling, &out.HostTooling
		*out = new(HostToolingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalSpec) DeepCopyInto(out *ApprovalSpec) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalSpec.
func (in *ApprovalSpec) DeepCopy() *ApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveSpec) DeepCopyInto(out *ArchiveSpec) {
	*out = *in
	if in.ClickHouse != nil {
		in, out := &in.ClickHouse, &out.ClickHouse
		*out = new(DependencySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveSpec.
func (in *ArchiveSpec) DeepCopy() *ArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(ArchiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(SecretReference)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencySpec) DeepCopyInto(out *DependencySpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencySpec.
func (in *DependencySpec) DeepCopy() *DependencySpec {
	if in == nil {
		return nil
	}
	out := new(DependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestructiveExecutionSpec) DeepCopyInto(out *DestructiveExecutionSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestructiveExecutionSpec.
func (in *DestructiveExecutionSpec) DeepCopy() *DestructiveExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(DestructiveExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMaintenanceWindow) DeepCopyInto(out *GPUMaintenanceWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMaintenanceWindow.
func (in *GPUMaintenanceWindow) DeepCopy() *GPUMaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(GPUMaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUMaintenanceWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMaintenanceWindowList) DeepCopyInto(out *GPUMaintenanceWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUMaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMaintenanceWindowList.
func (in *GPUMaintenanceWindowList) DeepCopy() *GPUMaintenanceWindowList {
	if in == nil {
		return nil
	}
	out := new(GPUMaintenanceWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUMaintenanceWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMaintenanceWindowSpec) DeepCopyInto(out *GPUMaintenanceWindowSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.StartsAt != nil {
		in, out := &in.StartsAt, &out.StartsAt
		*out = (*in).DeepCopy()
	}
	if in.EndsAt != nil {
		in, out := &in.EndsAt, &out.EndsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMaintenanceWindowSpec.
func (in *GPUMaintenanceWindowSpec) DeepCopy() *GPUMaintenanceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(GPUMaintenanceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMaintenanceWindowStatus) DeepCopyInto(out *GPUMaintenanceWindowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMaintenanceWindowStatus.
func (in *GPUMaintenanceWindowStatus) DeepCopy() *GPUMaintenanceWindowStatus {
	if in == nil {
		return nil
	}
	out := new(GPUMaintenanceWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfig) DeepCopyInto(out *GPUNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfig.
func (in *GPUNodeConfig) DeepCopy() *GPUNodeConfig {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigList) DeepCopyInto(out *GPUNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigList.
func (in *GPUNodeConfigList) DeepCopy() *GPUNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigSpec) DeepCopyInto(out *GPUNodeConfigSpec) {
	*out = *in
	if in.SSHSecretRef != nil {
		in, out := &in.SSHSecretRef, &out.SSHSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.BMCSecretRef != nil {
		in, out := &in.BMCSecretRef, &out.BMCSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigSpec.
func (in *GPUNodeConfigSpec) DeepCopy() *GPUNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigStatus) DeepCopyInto(out *GPUNodeConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentLastSeen != nil {
		in, out := &in.AgentLastSeen, &out.AgentLastSeen
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigStatus.
func (in *GPUNodeConfigStatus) DeepCopy() *GPUNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPlaybook) DeepCopyInto(out *GPUPlaybook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPlaybook.
func (in *GPUPlaybook) DeepCopy() *GPUPlaybook {
	if in == nil {
		return nil
	}
	out := new(GPUPlaybook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPlaybook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPlaybookList) DeepCopyInto(out *GPUPlaybookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUPlaybook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPlaybookList.
func (in *GPUPlaybookList) DeepCopy() *GPUPlaybookList {
	if in == nil {
		return nil
	}
	out := new(GPUPlaybookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPlaybookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPlaybookSpec) DeepCopyInto(out *GPUPlaybookSpec) {
	*out = *in
	if in.Effects != nil {
		in, out := &in.Effects, &out.Effects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]PlaybookStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnFailure != nil {
		in, out := &in.OnFailure, &out.OnFailure
		*out = new(PlaybookFailure)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPlaybookSpec.
func (in *GPUPlaybookSpec) DeepCopy() *GPUPlaybookSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPlaybookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPlaybookStatus) DeepCopyInto(out *GPUPlaybookStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPlaybookStatus.
func (in *GPUPlaybookStatus) DeepCopy() *GPUPlaybookStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPlaybookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURemediationPolicy) DeepCopyInto(out *GPURemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURemediationPolicy.
func (in *GPURemediationPolicy) DeepCopy() *GPURemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(GPURemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURemediationPolicyList) DeepCopyInto(out *GPURemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPURemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURemediationPolicyList.
func (in *GPURemediationPolicyList) DeepCopy() *GPURemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(GPURemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURemediationPolicySpec) DeepCopyInto(out *GPURemediationPolicySpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURemediationPolicySpec.
func (in *GPURemediationPolicySpec) DeepCopy() *GPURemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GPURemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURemediationPolicyStatus) DeepCopyInto(out *GPURemediationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURemediationPolicyStatus.
func (in *GPURemediationPolicyStatus) DeepCopy() *GPURemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GPURemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSignalMapping) DeepCopyInto(out *GPUSignalMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSignalMapping.
func (in *GPUSignalMapping) DeepCopy() *GPUSignalMapping {
	if in == nil {
		return nil
	}
	out := new(GPUSignalMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUSignalMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSignalMappingList) DeepCopyInto(out *GPUSignalMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUSignalMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSignalMappingList.
func (in *GPUSignalMappingList) DeepCopy() *GPUSignalMappingList {
	if in == nil {
		return nil
	}
	out := new(GPUSignalMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUSignalMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSignalMappingSpec) DeepCopyInto(out *GPUSignalMappingSpec) {
	*out = *in
	if in.XIDCodes != nil {
		in, out := &in.XIDCodes, &out.XIDCodes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSignalMappingSpec.
func (in *GPUSignalMappingSpec) DeepCopy() *GPUSignalMappingSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSignalMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSignalMappingStatus) DeepCopyInto(out *GPUSignalMappingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSignalMappingStatus.
func (in *GPUSignalMappingStatus) DeepCopy() *GPUSignalMappingStatus {
	if in == nil {
		return nil
	}
	out := new(GPUSignalMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostToolingSpec) DeepCopyInto(out *HostToolingSpec) {
	*out = *in
	if in.LibDirs != nil {
		in, out := &in.LibDirs, &out.LibDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostToolingSpec.
func (in *HostToolingSpec) DeepCopy() *HostToolingSpec {
	if in == nil {
		return nil
	}
	out := new(HostToolingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeNeuron) DeepCopyInto(out *KubeNeuron) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeNeuron.
func (in *KubeNeuron) DeepCopy() *KubeNeuron {
	if in == nil {
		return nil
	}
	out := new(KubeNeuron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeNeuron) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeNeuronList) DeepCopyInto(out *KubeNeuronList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeNeuron, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeNeuronList.
func (in *KubeNeuronList) DeepCopy() *KubeNeuronList {
	if in == nil {
		return nil
	}
	out := new(KubeNeuronList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeNeuronList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeNeuronSpec) DeepCopyInto(out *KubeNeuronSpec) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
	in.Agent.DeepCopyInto(&out.Agent)
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Safety.DeepCopyInto(&out.Safety)
	in.Approvals.DeepCopyInto(&out.Approvals)
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowStore.DeepCopyInto(&out.WorkflowStore)
	in.Observability.DeepCopyInto(&out.Observability)
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(ArchiveSpec)
		(*in).DeepCopyInto(*out)
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeNeuronSpec.
func (in *KubeNeuronSpec) DeepCopy() *KubeNeuronSpec {
	if in == nil {
		return nil
	}
	out := new(KubeNeuronSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeNeuronStatus) DeepCopyInto(out *KubeNeuronStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeNeuronStatus.
func (in *KubeNeuronStatus) DeepCopy() *KubeNeuronStatus {
	if in == nil {
		return nil
	}
	out := new(KubeNeuronStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationsSpec) DeepCopyInto(out *NotificationsSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SecretReference)
		**out = **in
	}
	if in.OperatorAPIToken != nil {
		in, out := &in.OperatorAPIToken, &out.OperatorAPIToken
		*out = new(SecretReference)
		**out = **in
	}
	if in.WebhookToken != nil {
		in, out := &in.WebhookToken, &out.WebhookToken
		*out = new(SecretReference)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(SecretReference)
		**out = **in
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationsSpec.
func (in *NotificationsSpec) DeepCopy() *NotificationsSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCSpec) DeepCopyInto(out *OIDCSpec) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
	if in.AllowedEmailDomains != nil {
		in, out := &in.AllowedEmailDomains, &out.AllowedEmailDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCSpec.
func (in *OIDCSpec) DeepCopy() *OIDCSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	in.VictoriaMetrics.DeepCopyInto(&out.VictoriaMetrics)
	in.Alertmanager.DeepCopyInto(&out.Alertmanager)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookFailure) DeepCopyInto(out *PlaybookFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookFailure.
func (in *PlaybookFailure) DeepCopy() *PlaybookFailure {
	if in == nil {
		return nil
	}
	out := new(PlaybookFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookStep) DeepCopyInto(out *PlaybookStep) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookStep.
func (in *PlaybookStep) DeepCopy() *PlaybookStep {
	if in == nil {
		return nil
	}
	out := new(PlaybookStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLiteStoreSpec) DeepCopyInto(out *SQLiteStoreSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLiteStoreSpec.
func (in *SQLiteStoreSpec) DeepCopy() *SQLiteStoreSpec {
	if in == nil {
		return nil
	}
	out := new(SQLiteStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetySpec) DeepCopyInto(out *SafetySpec) {
	*out = *in
	if in.DestructiveExecution != nil {
		in, out := &in.DestructiveExecution, &out.DestructiveExecution
		*out = new(DestructiveExecutionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetySpec.
func (in *SafetySpec) DeepCopy() *SafetySpec {
	if in == nil {
		return nil
	}
	out := new(SafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalMatch) DeepCopyInto(out *SignalMatch) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalMatch.
func (in *SignalMatch) DeepCopy() *SignalMatch {
	if in == nil {
		return nil
	}
	out := new(SignalMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.ServerSecretRef != nil {
		in, out := &in.ServerSecretRef, &out.ServerSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.ClientCASecretRef != nil {
		in, out := &in.ClientCASecretRef, &out.ClientCASecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.ServerCASecretRef != nil {
		in, out := &in.ServerCASecretRef, &out.ServerCASecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.PublicServerSecretRef != nil {
		in, out := &in.PublicServerSecretRef, &out.PublicServerSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStoreSpec) DeepCopyInto(out *WorkflowStoreSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.SQLite != nil {
		in, out := &in.SQLite, &out.SQLite
		*out = new(SQLiteStoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStoreSpec.
func (in *WorkflowStoreSpec) DeepCopy() *WorkflowStoreSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowStoreSpec)
	in.DeepCopyInto(out)
	return out
}
